/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendafrutas;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author ESFOT
 */
public class TiendaFrutas extends javax.swing.JFrame {
ArrayList<Frutas> listaFrutas=new ArrayList<Frutas>();
ArrayList<Frutas> listaFrutaSel=new ArrayList<Frutas>();
ArrayList<Clientes> listaClienteSel=new ArrayList<Clientes>();

DefaultComboBoxModel listaFrutasModel =
        new DefaultComboBoxModel(listaFrutas.toArray());
 Frutas f1;
 Frutas f2;  
 Frutas f3;  
 Frutas f4;  
 Frutas f5; 

ArrayList<Clientes> listaClientes=new ArrayList<Clientes>(); 
DefaultComboBoxModel listaClientesModel =
        new DefaultComboBoxModel(listaClientes.toArray());
    /**
     * Creates new form TiendaFrutas
     */
    public TiendaFrutas() {
        initComponents();
      f1=new Frutas("Manzana","1",0.30);  
      f2=new Frutas("Pera","2",0.25);  
      f3=new Frutas("Uva","3",0.60);  
      f4=new Frutas("Naranja","4",0.50 );  
      f5=new Frutas("Limon","5",0.50);  
        
     
      listaFrutasModel.addElement(f1.getNombre());
      listaFrutasModel.addElement(f2.getNombre());
      listaFrutasModel.addElement(f3.getNombre());
      listaFrutasModel.addElement(f4.getNombre());
      listaFrutasModel.addElement(f5.getNombre());
      
      cmbListaFrutas.setModel(listaFrutasModel);
      cmbListaCedulas.setModel(listaClientesModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        lblCedulaCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtCedulaCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbListaFrutas = new javax.swing.JComboBox<>();
        lblListaFrutas = new javax.swing.JLabel();
        lblCodigoFrutas = new javax.swing.JLabel();
        lblNombreFrutas = new javax.swing.JLabel();
        lblPrecioFrutas = new javax.swing.JLabel();
        bntAgregarFruta = new javax.swing.JButton();
        txtCodigoFrutas = new javax.swing.JTextField();
        txtNombreFrutas = new javax.swing.JTextField();
        txtPrecioFrutas = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblNombrePedido = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ListaCedulas = new javax.swing.JLabel();
        cmbListaCedulas = new javax.swing.JComboBox<>();
        bntMostrarPedido = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblCedulaPedido = new javax.swing.JLabel();
        txtNombrePedido = new javax.swing.JTextField();
        txtCedulaPedido = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAPedido = new javax.swing.JTextArea();
        lblTotal = new javax.swing.JLabel();
        lblTotalN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cliente");

        lblNombreCliente.setText("Nombre:");

        lblCedulaCliente.setText("Cedula:");

        jLabel4.setText("Frutas");

        lblListaFrutas.setText("Lista de frutas: ");

        lblCodigoFrutas.setText("Codigo:");

        lblNombreFrutas.setText("Nombre:");

        lblPrecioFrutas.setText("Precio:");

        bntAgregarFruta.setText("Agregar fruta al pedido");
        bntAgregarFruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAgregarFrutaActionPerformed(evt);
            }
        });

        jButton1.setText("Informacion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreCliente)
                            .addComponent(lblCedulaCliente))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreFrutas)
                            .addComponent(lblCodigoFrutas)
                            .addComponent(lblListaFrutas)
                            .addComponent(lblPrecioFrutas)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntAgregarFruta)
                        .addGap(35, 35, 35)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPrecioFrutas)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addComponent(txtCodigoFrutas)
                            .addComponent(txtNombreFrutas)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(cmbListaFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCliente)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbListaFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblListaFrutas)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoFrutas)
                    .addComponent(txtCodigoFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCedulaCliente)
                            .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreFrutas)
                            .addComponent(txtNombreFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrecioFrutas)
                    .addComponent(txtPrecioFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(bntAgregarFruta)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cliente / Frutas", jPanel1);

        jLabel2.setText("PEDIDOS REGISTRADOS");

        ListaCedulas.setText("Lista de cedulas:");

        bntMostrarPedido.setText("Mostrar Pedido");
        bntMostrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMostrarPedidoActionPerformed(evt);
            }
        });

        jLabel5.setText("Informacion del Cliente");

        jLabel6.setText("Pedidos del Cliente");

        jLabel7.setText("Nombre: ");

        lblCedulaPedido.setText("Cedula: ");

        txtCedulaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaPedidoActionPerformed(evt);
            }
        });

        txtAPedido.setColumns(20);
        txtAPedido.setRows(5);
        jScrollPane1.setViewportView(txtAPedido);

        lblTotal.setText("Total:");

        lblTotalN.setText("jLabel10");

        javax.swing.GroupLayout lblNombrePedidoLayout = new javax.swing.GroupLayout(lblNombrePedido);
        lblNombrePedido.setLayout(lblNombrePedidoLayout);
        lblNombrePedidoLayout.setHorizontalGroup(
            lblNombrePedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblNombrePedidoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(lblNombrePedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblNombrePedidoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel6))
                    .addComponent(jLabel2)
                    .addGroup(lblNombrePedidoLayout.createSequentialGroup()
                        .addGroup(lblNombrePedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(lblNombrePedidoLayout.createSequentialGroup()
                                .addComponent(ListaCedulas)
                                .addGap(18, 18, 18)
                                .addComponent(cmbListaCedulas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(lblNombrePedidoLayout.createSequentialGroup()
                                .addGroup(lblNombrePedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblNombrePedidoLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(lblNombrePedidoLayout.createSequentialGroup()
                                        .addComponent(lblCedulaPedido)
                                        .addGap(8, 8, 8)))
                                .addGroup(lblNombrePedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCedulaPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(txtNombrePedido))
                                .addGap(37, 37, 37)))
                        .addGroup(lblNombrePedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblNombrePedidoLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(bntMostrarPedido))
                            .addGroup(lblNombrePedidoLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(lblNombrePedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(lblNombrePedidoLayout.createSequentialGroup()
                                        .addComponent(lblTotal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTotalN))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        lblNombrePedidoLayout.setVerticalGroup(
            lblNombrePedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblNombrePedidoLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addGroup(lblNombrePedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListaCedulas)
                    .addComponent(cmbListaCedulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntMostrarPedido))
                .addGap(35, 35, 35)
                .addGroup(lblNombrePedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(lblNombrePedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblNombrePedidoLayout.createSequentialGroup()
                        .addGroup(lblNombrePedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNombrePedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(lblNombrePedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCedulaPedido)
                            .addComponent(txtCedulaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblNombrePedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal)
                    .addComponent(lblTotalN))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar Pedido", lblNombrePedido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaPedidoActionPerformed
Clientes c1;
    private void bntAgregarFrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAgregarFrutaActionPerformed
        // TODO add your handling code here:
        String nombreCliente= txtNombreCliente.getText();
        String cedula= txtCedulaCliente.getText();
        String nombrefruta=txtNombreFrutas.getText();
        String precio=txtPrecioFrutas.getText();
        String codigo=txtCodigoFrutas.getText();
        
        if(!(txtNombreCliente.getText().equals("")&&txtCedulaCliente.getText().equals("")&&txtNombreFrutas.getText().equals("")&&txtPrecioFrutas.getText().equals("")&&txtCodigoFrutas.getText().equals(""))){
          Frutas frutaSel=new Frutas(nombrefruta,codigo,Double.valueOf(codigo));
          listaFrutaSel.add(frutaSel);
            
            c1=new Clientes(nombreCliente,cedula,listaFrutaSel);
            listaClienteSel.add(c1);
            listaClientesModel.addElement(c1.getCedula());
          
        }else{
            JOptionPane.showMessageDialog(rootPane,"Llene todos los campos");
        }
        
        
       // String nombrefuta=
        
    }//GEN-LAST:event_bntAgregarFrutaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String frutas=cmbListaFrutas.getSelectedItem().toString();
        if(frutas.equals(f1.getNombre())){
            txtCodigoFrutas.setText(f1.getCodigo());
            txtNombreFrutas.setText(f1.getNombre());
            String precio=String.valueOf(f1.getPrecio());
            txtPrecioFrutas.setText(precio);
            
        }else if(frutas.equals(f2.getNombre())){
            txtCodigoFrutas.setText(f2.getCodigo());
            txtNombreFrutas.setText(f2.getNombre());
            String precio=String.valueOf(f2.getPrecio());
            txtPrecioFrutas.setText(precio);
        }else if(frutas.equals(f3.getNombre())){
            txtCodigoFrutas.setText(f3.getCodigo());
            txtNombreFrutas.setText(f3.getNombre());
            String precio=String.valueOf(f3.getPrecio());
            txtPrecioFrutas.setText(precio);
        }else if(frutas.equals(f4.getNombre())){
            txtCodigoFrutas.setText(f4.getCodigo());
            txtNombreFrutas.setText(f4.getNombre());
            String precio=String.valueOf(f4.getPrecio());
            txtPrecioFrutas.setText(precio);
        }else if(frutas.equals(f5.getNombre())){
            txtCodigoFrutas.setText(f5.getCodigo());
            txtNombreFrutas.setText(f5.getNombre());
            String precio=String.valueOf(f5.getPrecio());
            txtPrecioFrutas.setText(precio);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bntMostrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMostrarPedidoActionPerformed
        // TODO add your handling code here:
        String ced=cmbListaCedulas.getSelectedItem().toString();
        if(ced.equals(c1.getCedula())){
            txtNombrePedido.setText(c1.getNombre());
            txtCedulaPedido.setText(c1.getCedula());
          for(Object Itx:listaClienteSel){
               
          }
            
            
        }
    }//GEN-LAST:event_bntMostrarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiendaFrutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiendaFrutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiendaFrutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiendaFrutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiendaFrutas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ListaCedulas;
    private javax.swing.JButton bntAgregarFruta;
    private javax.swing.JButton bntMostrarPedido;
    private javax.swing.JComboBox<String> cmbListaCedulas;
    private javax.swing.JComboBox<String> cmbListaFrutas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCedulaCliente;
    private javax.swing.JLabel lblCedulaPedido;
    private javax.swing.JLabel lblCodigoFrutas;
    private javax.swing.JLabel lblListaFrutas;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNombreFrutas;
    private javax.swing.JPanel lblNombrePedido;
    private javax.swing.JLabel lblPrecioFrutas;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalN;
    private javax.swing.JTextArea txtAPedido;
    private javax.swing.JTextField txtCedulaCliente;
    private javax.swing.JTextField txtCedulaPedido;
    private javax.swing.JTextField txtCodigoFrutas;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreFrutas;
    private javax.swing.JTextField txtNombrePedido;
    private javax.swing.JTextField txtPrecioFrutas;
    // End of variables declaration//GEN-END:variables
}
